// <auto-generated />
using System;
using JobTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobTracker.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<int?>("JobApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("job_application_id");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("text")
                        .HasColumnName("linked_in_url");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_contacts");

                    b.HasIndex("JobApplicationId")
                        .HasDatabaseName("ix_contacts_job_application_id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interview_date");

                    b.Property<string>("InterviewerName")
                        .HasColumnType("text")
                        .HasColumnName("interviewer_name");

                    b.Property<int?>("JobApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("job_application_id");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text")
                        .HasColumnName("meeting_link");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_interviews");

                    b.HasIndex("JobApplicationId")
                        .HasDatabaseName("ix_interviews_job_application_id");

                    b.ToTable("interviews", (string)null);
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime?>("DateApplied")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_applied");

                    b.Property<string>("JobDescription")
                        .HasColumnType("text")
                        .HasColumnName("job_description");

                    b.Property<string>("JobPostingUrl")
                        .HasColumnType("text")
                        .HasColumnName("job_posting_url");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("text")
                        .HasColumnName("salary_range");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_job_applications");

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.Contact", b =>
                {
                    b.HasOne("JobTracker.Domain.Entities.JobApplication", "jobApplication")
                        .WithMany("contacts")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contacts_job_applications_job_application_id");

                    b.Navigation("jobApplication");
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.Interview", b =>
                {
                    b.HasOne("JobTracker.Domain.Entities.JobApplication", "jobApplication")
                        .WithMany("interviews")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_interviews_job_applications_job_application_id");

                    b.Navigation("jobApplication");
                });

            modelBuilder.Entity("JobTracker.Domain.Entities.JobApplication", b =>
                {
                    b.Navigation("contacts");

                    b.Navigation("interviews");
                });
#pragma warning restore 612, 618
        }
    }
}
